# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media.ui',
# licensing of 'media.ui' applies.
#
# Created: Thu Jul 18 09:57:34 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ecranWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecranWidget.sizePolicy().hasHeightForWidth())
        self.ecranWidget.setSizePolicy(sizePolicy)
        self.ecranWidget.setObjectName("ecranWidget")
        self.verticalLayout_2.addWidget(self.ecranWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tempLecture = QtWidgets.QLabel(self.centralwidget)
        self.tempLecture.setObjectName("tempLecture")
        self.horizontalLayout_5.addWidget(self.tempLecture)
        self.barreLect = QtWidgets.QSlider(self.centralwidget)
        self.barreLect.setOrientation(QtCore.Qt.Horizontal)
        self.barreLect.setObjectName("barreLect")
        self.horizontalLayout_5.addWidget(self.barreLect)
        self.tempRestant = QtWidgets.QLabel(self.centralwidget)
        self.tempRestant.setObjectName("tempRestant")
        self.horizontalLayout_5.addWidget(self.tempRestant)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbLecture = QtWidgets.QPushButton(self.centralwidget)
        self.pbLecture.setObjectName("pbLecture")
        self.horizontalLayout_2.addWidget(self.pbLecture)
        self.pbPause = QtWidgets.QPushButton(self.centralwidget)
        self.pbPause.setObjectName("pbPause")
        self.horizontalLayout_2.addWidget(self.pbPause)
        self.pbPause_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pbPause_2.setObjectName("pbPause_2")
        self.horizontalLayout_2.addWidget(self.pbPause_2)
        self.pbPrecedent = QtWidgets.QPushButton(self.centralwidget)
        self.pbPrecedent.setObjectName("pbPrecedent")
        self.horizontalLayout_2.addWidget(self.pbPrecedent)
        self.pbSuivant = QtWidgets.QPushButton(self.centralwidget)
        self.pbSuivant.setObjectName("pbSuivant")
        self.horizontalLayout_2.addWidget(self.pbSuivant)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pbPlus = QtWidgets.QPushButton(self.centralwidget)
        self.pbPlus.setObjectName("pbPlus")
        self.horizontalLayout.addWidget(self.pbPlus)
        self.pbMoins = QtWidgets.QPushButton(self.centralwidget)
        self.pbMoins.setObjectName("pbMoins")
        self.horizontalLayout.addWidget(self.pbMoins)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setObjectName("dial")
        self.horizontalLayout_4.addWidget(self.dial)
        self.nivoVolume = QtWidgets.QLabel(self.centralwidget)
        self.nivoVolume.setObjectName("nivoVolume")
        self.horizontalLayout_4.addWidget(self.nivoVolume)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tempLecture.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.tempRestant.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.pbLecture.setText(QtWidgets.QApplication.translate("MainWindow", "Lecture", None, -1))
        self.pbPause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.pbPause_2.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pbPrecedent.setText(QtWidgets.QApplication.translate("MainWindow", "Precedent", None, -1))
        self.pbSuivant.setText(QtWidgets.QApplication.translate("MainWindow", "Suivant", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Liste de lecture :", None, -1))
        self.pbPlus.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pbMoins.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Volume :", None, -1))
        self.nivoVolume.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))

